# Generated by Django 3.0.4 on 2020-03-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedis', '0002_auto_20200311_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
