# Generated by Django 3.0.4 on 2020-03-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedis', '0004_auto_20200311_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
