# Generated by Django 3.0.4 on 2020-03-12 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedis', '0007_auto_20200311_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jedis.Jedi'),
        ),
        migrations.AlterField(
            model_name='jedi',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='jedi',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedis.Planet', verbose_name='Планета'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
    ]
